syntax = "proto3";

package bilibili.live.gift.v1;

import "bilibili/live/component/common_model/effect.proto";
import "bilibili/live/component/common_model/user_dagw.proto";

//
message EasterEggBenefit {
    //
    string material_url = 1;
    //
    string material_md5 = 2;
    //
    int64 effect_num = 3;
    //
    int64 effect_num_audience = 4;
    //
    string unlock_text = 5;
    //
    string web_material_url = 6;
    //
    string web_material_md5 = 7;
}

//
message FansLightAnimation {
    //
    string medal_name = 1;
}

//
message GiftBenefits {
    //
    EasterEggBenefit easter_egg = 1;
    //
    FansLightAnimation fans_light_animation = 2;
}

//
message GiftMaterialSnapShot {
    //
    string img_basic = 1;
    //
    string webp = 2;
    //
    int64 effect_id = 3;
    //
    int64 has_imaged_gift = 4;
    // gif图标（网页端定义中缺失，根据实际数据补充）
    string gif = 5;
}

//
message GroupMedalBrief {
    //
    int64 medal_id = 1;
    //
    string name = 2;
    //
    int64 is_lighted = 3;
}

//
message SendGiftBroadcast {
    //
    message BagGiftInfo {
        //
        int32 show_price = 1;
        //
        int64 price_for_show = 2;
    }

    //
    message BlindGift {
        //
        int64 blind_gift_config_id = 1;
        //
        int64 original_gift_id = 2;
        //
        string original_gift_name = 3;
        //
        int64 from = 4;
        //
        string gift_action = 5;
        //
        int64 original_gift_price = 6;
        //
        int64 gift_tip_price = 7;
    }

    //
    message FaceEffect {
        //
        int64 face_effect_type = 1;
        //
        repeated SendGiftBroadcast.FaceEffectItem candidate_face_effects = 2;
    }

    //
    message FaceEffectItem {
        //
        int64 effect_id = 1;
        //
        int64 source = 2;
    }

    //
    message FaceEffectV2 {
        //
        int64 id = 1;
        //
        int64 type = 2;
    }

    //
    message GiftItem {
        //
        int64 gift_id = 1;
        //
        string gift_name = 2;
        //
        int64 num = 3;
        //
        int64 demarcation = 4;
        //
        int64 price = 5;
        //
        int64 discount_price = 6;
        //
        int64 total_coin = 7;
        //
        string coin_type = 8;
        //
        string tid = 9;
        //
        int64 timestamp = 10;
        //
        int64 super_batch_gift_num = 11;
        //
        string batch_combo_id = 12;
        //
        int64 combo_resources_id = 13;
        //
        int64 combo_total_coin = 14;
        //
        int64 combo_stay_time = 15;
        //
        float magnification = 16;
        //
        bool show_batch_combo_send = 17;
        //
        string action = 18;
        //
        int64 effect_block = 19;
        //
        int64 is_special_batch = 20;
        //
        int64 float_sc_resource_id = 21;
        //
        string tag_image = 22;
        //
        int64 crit_prob = 23;
        //
        int64 rcost = 24;
        //
        int64 test = 25;
        //
        int64 face_effect_type = 26;
        //
        int64 face_effect_id = 27;
        //
        bool is_naming = 28;
        //
        SendGiftBroadcast.ReceiveUserInfo receive_user_info = 29;
        //
        bool is_join_receiver = 30;
        //
        SendGiftBroadcast.BagGiftInfo bag_gift = 31;
        //
        repeated int64 gift_tag = 32;
        //
        bilibili.live.component.common_model.user_dagw.UserInfo receiver_uinfo = 33;
        //
        SendGiftBroadcast.FaceEffectV2 face_effect_v2 = 34;
        //
        GiftMaterialSnapShot gift_info = 35;
        //
        int64 gift_tip_price = 36;
        //
        SendGiftBroadcast.FaceEffect face_effect = 37;
        //
        GiftBenefits benefits = 38;
        //
        bilibili.live.component.common_model.effect.EffectConfigItem effect_config = 39;
    }

    //
    message MedalInfo {
        //
        int64 target_id = 1;
        //
        string special = 2;
        //
        string anchor_uname = 3;
        //
        int64 anchor_roomid = 4;
        //
        int64 medal_level = 5;
        //
        string medal_name = 6;
        //
        int64 medal_color = 7;
        //
        int64 medal_color_start = 8;
        //
        int64 medal_color_end = 9;
        //
        int64 medal_color_border = 10;
        //
        int64 is_lighted = 11;
        //
        int64 guard_level = 12;
    }

    //
    message ReceiveUserInfo {
        //
        string uname = 1;
        //
        int64 uid = 2;
    }

    //
    message SendMaster {
        //
        int64 uid = 1;
        //
        string uname = 2;
    }

    //
    message WealthInfo {
        //
        int64 level = 1;
    }

    //
    int64 uid = 1;
    //
    string uname = 2;
    //
    string face = 3;
    //
    string name_color = 4;
    //
    int64 guard_level = 5;
    //
    int64 svga_block = 6;
    //
    SendGiftBroadcast.SendMaster send_master = 7;
    //
    SendGiftBroadcast.MedalInfo medal_info = 8;
    //
    SendGiftBroadcast.BlindGift blind_gift = 9;
    //
    repeated SendGiftBroadcast.GiftItem gift_list = 10;
    //
    bool switch = 11;
    //
    int64 test = 12;
    //
    SendGiftBroadcast.WealthInfo wealth_info = 13;
    //
    GroupMedalBrief group_medal = 14;
    //
    bilibili.live.component.common_model.user_dagw.UserInfo sender_uinfo = 15;
}
